//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPanda.NRegistry.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NPanda.NRegistry.Resources.ExceptionStrings", typeof(ExceptionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read value {0} in key {1}; the key could not be found..
        /// </summary>
        internal static string AbsentKey {
            get {
                return ResourceManager.GetString("AbsentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create dynamic proxy object from type {0}; it is not marked as a Key and cannot be used by NRegistry. Decorate the type with KeyAttribute. .
        /// </summary>
        internal static string AbsentKeyAttribute {
            get {
                return ResourceManager.GetString("AbsentKeyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create dynamic proxy object from type {0}; it is not accessibly to NRegistry. Change the type&apos;s accessibility to public..
        /// </summary>
        internal static string InaccessibleType {
            get {
                return ResourceManager.GetString("InaccessibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create dynamic proxy object from type {0}; it is sealed and cannot be inherited by NRegistry. Remove the type&apos;s sealed modifier..
        /// </summary>
        internal static string SealedClass {
            get {
                return ResourceManager.GetString("SealedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create dynamic proxy object from type {0}; method {1} is marked as a Value but is not virtual and cannot be inherited by NRegistry. Set the method as virtual..
        /// </summary>
        internal static string SealedValueMethod {
            get {
                return ResourceManager.GetString("SealedValueMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create dynamic proxy object from type {0}; property {1} is marked as a Value but is not virtual and cannot be inherited by NRegistry. Set the property as virtual..
        /// </summary>
        internal static string SealedValueProperty {
            get {
                return ResourceManager.GetString("SealedValueProperty", resourceCulture);
            }
        }
    }
}
